# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2fd24a3ae4c348bcddad1976cfa16a5cba76d1686dc05834adc089f51299b4dc9f2cd60267a108307af83e3f46423a2af7ca55092dbefd3c7684fe4dc19d28b

test:
  secret_key_base: ff34baffd266c24927118c82ca289395c8ca1e7fc2f582f9604bbb6dc430eca33713e7167d282ab4c9403bb33169c6009c5fad6f3e1ae53e56e7216dc8e98014

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
